[package]
name = "nuprompt"
<<<<<<< ours
version = "0.4.4"
||||||| ancestor
version = "0.4.2"
=======
version = "0.4.3"
>>>>>>> theirs
edition = "2021"

[dependencies]
git2 = { version = "0.19.0", default-features = false, features = ["vendored-libgit2"] }
users = { version = "0.11.0", default-features = false }
log = { version = "0.4.22", default-features = false }
env_logger = { version = "0.11.5", default-features = false }
anyhow = { version = "1.0.94", default-features = false }
coarsetime = { version = "0.1.35", default-features = false }
termcolor = { version = "1.4.1", default-features = false }
