name: ci
on:
  pull_request:
    branches: [ "*" ]
  push:
    branches:
      - main
env:
  CARGO_TERM_COLOR: always
jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - run: cargo build --release
    - run: cargo clippy
    - run: git diff --exit-code
  release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: ci
    permissions:
      contents: write
    steps:
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        set -exu
        version=$(cargo read-manifest | jq -r .version)
        if gh release view ${version}; then
          echo "release already exists"
        else
          gh release create ${version} -t ${version} --generate-notes
        fi
